# Generated by Django 3.1.5 on 2021-03-04 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='consignment',
            name='arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='departure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shipper.line'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='consignment_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shipper.shipper'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='status',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shipper.vessel'),
        ),
        migrations.AlterField(
            model_name='line',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vessel_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='file_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
